from enum import Enum


class StatsType(str, Enum):
    OPCODES_PER_BLOCK = 'OPCODES_PER_BLOCK'
    TOTAL_AMOUNT_OPCODES = 'TOTAL_AMOUNT_OPCODES'
    OPCODE_COUNTS = 'OPCODE_COUNTS'
    OPCODE_STATS = 'OPCODE_STATS'
    OPCODE_BLOCK_FREQUENCY = 'OPCODE_BLOCK_FREQUENCY'